AWSTemplateFormatVersion: "2010-09-09"

Description: This example consist to create a new DynamoDB table with an string key

Metadata:
  Comments:
    ScoreTable: Create Tables with Cloudformation tables

Parameters:
  TableName:
    Description: Table name
    Type: String
  Environment:
    Description: Environment to deploy
    Type: String

Conditions:
  IsProductionEnvironment:
    Fn::Equals:
    - ${self:custom.stage}
    - prd
Mappings:
  Environment:
    Production:
      ReadCapacityUnits: 2
      WriteCapacityUnits: 2
    Stage:
      ReadCapacityUnits: 2
      WriteCapacityUnits: 2

Resources:
  DynamoDbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
      - AttributeName: UserId
        AttributeType: S
      - AttributeName: Game
        AttributeType: S
      KeySchema:
      - AttributeName: UserId
        KeyType: HASH
      - AttributeName: Game
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits:
          Fn::FindInMap:
          - Environment
          - Ref: Environment
          - ReadCapacityUnits
        WriteCapacityUnits:
          Fn::FindInMap:
          - Environment
          - Ref: Environment
          - WriteCapacityUnits
      Tags:
      - Key: Name
        Value:
          Ref: TableName
      - Key: Environment
        Value:
          Ref: Environment

Outputs:
  DynamoDBTableArn:
    Description: DynamoDB ARN
    Value:
      Fn::GetAtt:
      - DynamoDbTable
      - Arn
    Export:
      Name: !Sub 'DynamoDBTableArn-${Environment}'
