AWSTemplateFormatVersion: "2010-09-09"

Description: "This example consist to create a new DynamoDB table with an string key"

Metadata:
  Comments:
    ScoreTable: "Score tables"
Parameters:
  TableName:
    Description: "Table name"
    Type: String

# Mappings:
#   set of mappings

# Conditions:
#   set of conditions

# Transform:
#   set of transforms

Resources:
  ScoreTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        -
          AttributeName: "UserId"
          AttributeType: "S"
        -
          AttributeName: "Game"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "UserId"
          KeyType: "HASH"
        -
          AttributeName: "Game"
          KeyType: "RANGE"
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
      Tags:
        -
          Key: "Name"
          Value: "demo-scores-cloudformation"
        -
          Key: "Environment"
          Value: "demo"
